from scraper.pipeline.embedding import generate_embedding


def normalize_tool(tool):

    name = tool.get("name")

    description = tool.get("description", "")

    category = tool.get("category", "AI Tool")

    website = tool.get("website")

    embedding = generate_embedding(description)

    normalized = {

        # id auto-generated by Supabase

        "name": name,

        "description": description,

        "category": category,

        "tags": [
            "ai",
            category.lower().replace(" ", "_")
        ],

        "url": website,

        "website": website,

        "rating": None,

        "pricing": None,

        "embedding": embedding,

        "approved": True,

        "added_by": "scraper"
    }

    return normalized